<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#For-each-of-the-following-questions,-formulate-a-null-and-alternative-hypothesis-(be-as-specific-as-you-can-be),-then-give-an-example-of-what-a-true-positive,-true-negative,-type-I-and-type-II-errors-would-look-like.-Note-that-some-of-the-questions-are-intentionally-phrased-in-a-vague-way.-It-is-your-job-to-reword-these-as-more-precise-questions-that-could-be-tested." data-toc-modified-id="For-each-of-the-following-questions,-formulate-a-null-and-alternative-hypothesis-(be-as-specific-as-you-can-be),-then-give-an-example-of-what-a-true-positive,-true-negative,-type-I-and-type-II-errors-would-look-like.-Note-that-some-of-the-questions-are-intentionally-phrased-in-a-vague-way.-It-is-your-job-to-reword-these-as-more-precise-questions-that-could-be-tested.-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.</a></span></li><li><span><a href="#Ace-Realty-wants-to-determine-whether-the-average-time-it-takes-to-sell-homes-is-different-for-its-two-offices.-A-sample-of-40-sales-from-office-#1-revealed-a-mean-of-90-days-and-a-standard-deviation-of-15-days.-A-sample-of-50-sales-from-office-#2-revealed-a-mean-of-100-days-and-a-standard-deviation-of-20-days.-Use-a-.05-level-of-significance." data-toc-modified-id="Ace-Realty-wants-to-determine-whether-the-average-time-it-takes-to-sell-homes-is-different-for-its-two-offices.-A-sample-of-40-sales-from-office-#1-revealed-a-mean-of-90-days-and-a-standard-deviation-of-15-days.-A-sample-of-50-sales-from-office-#2-revealed-a-mean-of-100-days-and-a-standard-deviation-of-20-days.-Use-a-.05-level-of-significance.-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.</a></span><ul class="toc-item"><li><span><a href="#Is-there-a-difference-in-fuel-efficiency-in-cars-from-2008-vs-1999?" data-toc-modified-id="Is-there-a-difference-in-fuel-efficiency-in-cars-from-2008-vs-1999?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Is there a difference in fuel-efficiency in cars from 2008 vs 1999?</a></span></li><li><span><a href="#Are-compact-cars-more-fuel-efficient-than-the-average-car?" data-toc-modified-id="Are-compact-cars-more-fuel-efficient-than-the-average-car?-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Are compact cars more fuel-efficient than the average car?</a></span></li></ul></li><li><span><a href="#Correlation" data-toc-modified-id="Correlation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Correlation</a></span><ul class="toc-item"><li><span><a href="#Use-the-telco_churn-data." data-toc-modified-id="Use-the-telco_churn-data.-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Use the telco_churn data.</a></span><ul class="toc-item"><li><span><a href="#Does-tenure-correlate-with-monthly-charges?" data-toc-modified-id="Does-tenure-correlate-with-monthly-charges?-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Does tenure correlate with monthly charges?</a></span></li><li><span><a href="#Does-tenure-correlate-with-total-charges?" data-toc-modified-id="Does-tenure-correlate-with-total-charges?-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Does tenure correlate with total charges?</a></span></li><li><span><a href="#What-happens-if-you-control-for-phone-and-internet-service?" data-toc-modified-id="What-happens-if-you-control-for-phone-and-internet-service?-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>What happens if you control for phone and internet service?</a></span></li></ul></li><li><span><a href="#Use-the-employees-database." data-toc-modified-id="Use-the-employees-database.-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Use the employees database.</a></span><ul class="toc-item"><li><span><a href="#Is-there-a-relationship-between-how-long-an-employee-has-been-with-the-company-and-their-salary?" data-toc-modified-id="Is-there-a-relationship-between-how-long-an-employee-has-been-with-the-company-and-their-salary?-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Is there a relationship between how long an employee has been with the company and their salary?</a></span></li><li><span><a href="#Is-there-a-relationship-between-how-long-an-employee-has-been-with-the-company-and-the-number-of-titles-they-have-had?" data-toc-modified-id="Is-there-a-relationship-between-how-long-an-employee-has-been-with-the-company-and-the-number-of-titles-they-have-had?-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Is there a relationship between how long an employee has been with the company and the number of titles they have had?</a></span></li></ul></li><li><span><a href="#Use-the-sleepstudy-data." data-toc-modified-id="Use-the-sleepstudy-data.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Use the sleepstudy data.</a></span><ul class="toc-item"><li><span><a href="#Is-there-a-relationship-between-days-and-reaction-time?" data-toc-modified-id="Is-there-a-relationship-between-days-and-reaction-time?-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Is there a relationship between days and reaction time?</a></span></li></ul></li></ul></li><li><span><a href="#Chi-Square-Testing" data-toc-modified-id="Chi-Square-Testing-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Chi Square Testing</a></span><ul class="toc-item"><li><span><a href="#Use-the-following-contingency-table-to-help-answer-the-question-of-whether-using-a-macbook-and-being-a-codeup-student-are-independent-of-each-other." data-toc-modified-id="Use-the-following-contingency-table-to-help-answer-the-question-of-whether-using-a-macbook-and-being-a-codeup-student-are-independent-of-each-other.-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.</a></span></li><li><span><a href="#Use-the-data-from-the-employees-database-to-answer-these-questions:" data-toc-modified-id="Use-the-data-from-the-employees-database-to-answer-these-questions:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Use the data from the employees database to answer these questions:</a></span></li></ul></li></ul></div>

In [1]:
from pydataset import data
from scipy import stats
import pandas as pd
import numpy as np
import env

# For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.

Has the network latency gone up since we switched internet service providers?

H_0: There is not a difference in latancy
    True Negative - There is no latancy change betweeen internet service providers
    False Negative - There is no change between providers, but sampling error indicated there was a difference. 
        * User decided to become a gamer, eating up major bandwidth playing multiplayer pacman
        * Netflix has consumed user's life
        * Disney+ won't let them go
        
Ha: There is a difference in latancy
    True Positive - Latency has gone up since changing providers
    False Positive -         
        * Users in the region have experienced an up tick in latency across the board from quarantine

Is the website redesign any good?

ho: traffic to website has not changed after the redesign
    true negative - there has been no change in the number of visitors to the site after the rework
    false negative - 
ha: traffic to website has increased after the redesign
    true positive - there has been a significant increase to the average number of visitors per day after the site rework
    false positive - A new website partnership began sending an increased number of visitors to the site

Is our television ad driving more sales?
h0: ad had no effect on sales
    true negative - no effect was shown, no sampling errors to account for
    false negative - sampling errors occurred that may indicate:
        * ad was not broadcasted to a large audience (maybe there was an issue broadcasting)
        * ad was broadcasted at the same time as puppy monkey baby
ha: ad had a positive impact on sales
    true positive: revenue has increased directly after sales with no alternative influencors on sales
    false positive: revenue has increased, however it was caused by:
        * swimsuit ad going on during the same time spring break is happening
        * jesus toilet paper ads must feel like a joke right now

# Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

Load the mpg dataset and use it to answer the following questions:

In [2]:
mpg = data('mpg')

# Create a average mpg based on (highway + city) / 2
mpg['avg_mpg'] = (mpg['hwy'] + mpg['cty']) / 2

mpg['is_auto'] = mpg.trans.str.contains('auto')

mpg.rename(columns={'class': 'is_compact'}, inplace=True)

mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p   
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p   
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p   

  is_compact  avg_mpg  is_auto  
1    compact     23.5     True  
2    compact     25.0    False  
3    compact     25.5    False  
4    compact     25.5     True  
5    compact     21.0     True

## Is there a difference in fuel-efficiency in cars from 2008 vs 1999?

Ho = there will be no difference in mpg 
Ha = cars from 2008 will be more fuel effecient

In [3]:
c_level = .05
alpha = 1 - c_level
x1 = mpg[mpg.year == 2008]['avg_mpg']
x2 = mpg[mpg.year == 1999]['avg_mpg']

In [4]:
t, p = stats.ttest_ind(x1, x2)
t, p, p < alpha

(-0.21960177245940962, 0.8263744040323578, True)

## Are compact cars more fuel-efficient than the average car?

Ho - Compact cars are similiarly fuel effecient to the average
Ha - compact cars are more fuel efficient

In [5]:
avg_comp_mpg = mpg[mpg.is_compact == 'compact']['avg_mpg']
avg_mpg = mpg.avg_mpg.mean()

t, p = stats.ttest_1samp(avg_comp_mpg, avg_mpg)
t, p

(7.896888573132535, 4.1985637943171336e-10)

Do manual cars get better gas mileage than automatic cars?

In [6]:
auto = mpg[mpg.is_auto == True]['avg_mpg']
manual = mpg[mpg.is_auto == False]['avg_mpg']

t, p = stats.ttest_ind(manual, auto)
t, p

(4.593437735750014, 7.154374401145683e-06)

# Correlation

## Use the telco_churn data.

In [7]:
telco_url = env.get_url_for_pancakes('telco_churn')

In [8]:
query = '''
SELECT * 
FROM customers
LEFT JOIN contract_types using(contract_type_id)'''

In [9]:
telco = pd.read_sql(query, telco_url, index_col='customer_id')
telco.total_charges = telco.total_charges.replace(' ', np.nan).astype(float)
telco = telco.dropna()

In [10]:
telco.head()

contract_type_id  gender  senior_citizen partner dependents  \
customer_id                                                                
0003-MKNFE                  1    Male               0      No         No   
0004-TLHLJ                  1    Male               0      No         No   
0011-IGKFF                  1    Male               1     Yes         No   
0013-EXCHZ                  1  Female               1     Yes         No   
0013-MHZWF                  1  Female               0      No        Yes   

             tenure phone_service multiple_lines  internet_service_type_id  \
customer_id                                                                  
0003-MKNFE        9           Yes            Yes                         1   
0004-TLHLJ        4           Yes             No                         2   
0011-IGKFF       13           Yes             No                         2   
0013-EXCHZ        3           Yes             No                         2   
0013-MHZWF        9           Yes             No                         1   

            online_security  ... device_protection tech_support streaming_tv  \
customer_id                  ...                                               
0003-MKNFE               No  ...                No           No           No   
0004-TLHLJ               No  ...               Yes           No           No   
0011-IGKFF               No  ...               Yes           No          Yes   
0013-EXCHZ               No  ...                No          Yes          Yes   
0013-MHZWF               No  ...                No          Yes          Yes   

            streaming_movies paperless_billing payment_type_id  \
customer_id                                                      
0003-MKNFE               Yes                No               2   
0004-TLHLJ                No               Yes               1   
0011-IGKFF               Yes               Yes               1   
0013-EXCHZ                No               Yes               2   
0013-MHZWF               Yes               Yes               4   

             monthly_charges  total_charges  churn   contract_type  
customer_id                                                         
0003-MKNFE              59.9         542.40     No  Month-to-month  
0004-TLHLJ              73.9         280.85    Yes  Month-to-month  
0011-IGKFF              98.0        1237.85    Yes  Month-to-month  
0013-EXCHZ              83.9         267.40    Yes  Month-to-month  
0013-MHZWF              69.4         571.45     No  Month-to-month  

[5 rows x 21 columns]

### Does tenure correlate with monthly charges? 

In [11]:
alpha = 0.05

x = telco[telco.contract_type.str.contains('Month')]['monthly_charges']
y = telco[telco.contract_type.str.contains('Month')]['tenure']

r, p = stats.pearsonr(x, y)
r, p

(0.3622745229296931, 1.6782903370120815e-120)

In [12]:
print(f''' 
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis.
''')

 
p (1.6782903370120815e-120) < alpha (0.05), therefor we reject the null hypothesis.



### Does tenure correlate with total charges?

In [13]:
x = telco.total_charges
y = telco.tenure

r, p = stats.pearsonr(x, y)
r, p

print(f''' 
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis.
''')

 
p (0.0) < alpha (0.05), therefor we reject the null hypothesis.



### What happens if you control for phone and internet service?

In [14]:
telco['has_internet'] = telco.internet_service_type_id != 3

In [15]:
telco['has_phone'] = telco.phone_service.str.contains('Yes')

In [16]:
telco['has_both'] = telco.has_internet & telco.has_phone

In [17]:
# monthly vs tenure if they have internet
x = telco[telco.has_internet]['monthly_charges']
y = telco[telco.has_internet]['tenure']

r, p = stats.pearsonr(x, y)
print(f''' 
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis.
''')

 
p (1.6186841401711697e-180) < alpha (0.05), therefor we reject the null hypothesis.



In [18]:
# monthly vs tenure if they have a phone
x = telco[telco.has_phone]['monthly_charges']
y = telco[telco.has_phone]['tenure']

r, p = stats.pearsonr(x, y)
print(f''' 
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis.
''')

 
p (6.82801603762022e-87) < alpha (0.05), therefor we reject the null hypothesis.



In [19]:
# monthly vs tenure if they have both a phone and internet service
x = telco[telco.has_both]['monthly_charges']
y = telco[telco.has_both]['tenure']

r, p = stats.pearsonr(x, y)
print(f''' 
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis.
''')

 
p (1.9985481080656104e-231) < alpha (0.05), therefor we reject the null hypothesis.



## Use the employees database.

In [20]:
employees_url = env.get_url_for_pancakes('employees')

query = '''
SELECT emp_no, datediff(curdate(), hire_date) as tenure, salaries.salary
FROM employees
JOIN salaries using (emp_no)
'''

employees = pd.read_sql(query, employees_url)

In [21]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2844047 entries, 0 to 2844046
Data columns (total 3 columns):
emp_no    int64
tenure    int64
salary    int64
dtypes: int64(3)
memory usage: 65.1 MB


### Is there a relationship between how long an employee has been with the company and their salary?

In [22]:
x = employees.tenure
y = employees.salary

r, p = stats.pearsonr(x, y)
r, p

print(f'''
p ({p}) < alpha ({alpha}), therefore we reject the null hypothesis.
''')


p (0.0) < alpha (0.05), therefore we reject the null hypothesis.



### Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [23]:
query = '''
SELECT COUNT(title) as title_count, DATEDIFF(CURDATE(), hire_date) as tenure
FROM titles
LEFT JOIN employees USING(emp_no)
GROUP BY emp_no
'''

titles = pd.read_sql(query, employees_url)

In [24]:
titles.head()

title_count  tenure
0            1   12327
1            1   12544
2            1   12264
3            2   12169
4            2   11153

In [25]:
x = titles.title_count
y = titles.tenure

In [26]:
r, p = stats.pearsonr(x, y)
r, p

(0.2665989299136619, 0.0)

In [27]:
print(f'''
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis
''')


p (0.0) < alpha (0.05), therefor we reject the null hypothesis



## Use the sleepstudy data. 

### Is there a relationship between days and reaction time?

In [28]:
from pydataset import data

In [29]:
sleep_study = data('sleepstudy')
sleep_study.head()

Reaction  Days  Subject
1  249.5600     0      308
2  258.7047     1      308
3  250.8006     2      308
4  321.4398     3      308
5  356.8519     4      308

In [30]:
x = sleep_study.Days
y = sleep_study.Reaction

In [31]:
r, p = stats.pearsonr(x, y)
r, p

(0.5352302262650253, 9.894096322214812e-15)

In [32]:
print(f'''
p ({p}) < alpha ({alpha}), therefor we reject the null hypothesis. 
''')


p (9.894096322214812e-15) < alpha (0.05), therefor we reject the null hypothesis. 



# Chi Square Testing

## Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

In [42]:
columns = ['codeup', 'not_codeup']
index = ['macbook', 'not_macbook']

mac = pd.DataFrame([[49, 20], [1, 30]], index=index, columns=columns)
mac

codeup  not_codeup
macbook          49          20
not_macbook       1          30

In [44]:
chi2, p, degf, expected = stats.chi2_contingency(mac)

In [47]:
print('Observed\n')
print(mac.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[34.5 34.5]
 [15.5 15.5]]
---

chi^2 = 36.6526
p     = 0.0000


Due to P value being less than the alpha of 0.05, we fail to reject the null hypothesis that there is no correlation between being a codeup student and owning a mac.

> Choose another 2 categorical variables from the mpg dataset and perform a 
c
h
i
2
 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [50]:
mpg.head(1)

manufacturer model  displ  year  cyl     trans drv  cty  hwy fl is_compact  \
1         audi    a4    1.8  1999    4  auto(l5)   f   18   29  p    compact   

   avg_mpg  is_auto  
1     23.5     True

Is there a correlation between type of transmission and manufacturer?

$H_0$ - There is no correlation

$H_1$ - There is a correlation

In [57]:
df = pd.crosstab(mpg.manufacturer, mpg.is_auto)

In [56]:
chi2, p, degf, expected = stats.chi2_contingency(df)

In [58]:
print('Observed\n')
print(mac.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[ 5.92307692 12.07692308]
 [ 6.25213675 12.74786325]
 [12.17521368 24.82478632]
 [ 8.22649573 16.77350427]
 [ 2.96153846  6.03846154]
 [ 4.60683761  9.39316239]
 [ 2.63247863  5.36752137]
 [ 1.31623932  2.68376068]
 [ 0.98717949  2.01282051]
 [ 1.31623932  2.68376068]
 [ 4.27777778  8.72222222]
 [ 1.64529915  3.35470085]
 [ 4.60683761  9.39316239]
 [11.18803419 22.81196581]
 [ 8.88461538 18.11538462]]
---

chi^2 = 29.2937
p     = 0.0095


## Use the data from the employees database to answer these questions:

In [94]:
query = """
SELECT e.gender, d.dept_name
FROM employees AS e
JOIN dept_emp as de USING(emp_no)
JOIN departments as d USING(dept_no)
WHERE de.to_date > NOW()
    AND d.dept_name IN ("Sales", "Marketing")
"""

url = env.get_url_for_pancakes('employees')

emp = pd.read_sql(query, url)
emp.dept_name.value_counts()

Sales        37701
Marketing    14842
Name: dept_name, dtype: int64

In [95]:
df = pd.crosstab(emp.gender, emp.dept_name)
df.head()

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

In [96]:
chi2_stat, p, degf, expected = stats.chi2_contingency(df)

In [97]:
print('Observed\n')
print(mac.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[ 5893.2426013 14969.7573987]
 [ 8948.7573987 22731.2426013]]
---

chi^2 = 29.2937
p     = 0.5692


Is an employee's gender independent of whether or not they are or have been a manager?

In [130]:
query = """
SELECT emp_no, gender
FROM employees
"""

url = env.get_url_for_pancakes('employees')

e = pd.read_sql(query, url)
e.head()

emp_no gender
0   10001      M
1   10002      F
2   10003      M
3   10004      M
4   10005      M

In [131]:
query = '''
SELECT emp_no
FROM dept_manager
'''

url = env.get_url_for_pancakes('employees')

dept_man = pd.read_sql(query, url)
dept_man.head()

emp_no
0  110022
1  110039
2  110085
3  110114
4  110183

In [132]:
e['manager'] = e.emp_no.isin(dept_man.emp_no)
e.manager.value_counts()

False    300000
True         24
Name: manager, dtype: int64

In [134]:
has_been_manager = pd.crosstab(e.gender, e.manager)
has_been_manager

manager   False  True 
gender                
F        120038     13
M        179962     11

In [137]:
chi2_stat, p, degf, expected = stats.chi2_contingency(has_been_manager)

In [138]:
print('Observed\n')
print(mac.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[1.20041397e+05 9.60331174e+00]
 [1.79958603e+05 1.43966883e+01]]
---

chi^2 = 29.2937
p     = 0.2275
